repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear==19.8.0]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    - id: pyupgrade
      args: [--py36-plus]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args:
      - --skip
      - B101