name: Lint and coverage workflow
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.9]
    env:
      PYTHON_VERSION: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
            python-version: $PYTHON_VERSION
            cache: "pip"

      - name: "Install and run pre-commit via tox"
        run: |
              python -m pip install tox==3.27.1 tox-gh-actions
              python -m tox -vv
