name: Codecov workflow
on: [push, pull_request]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: "Install and run pre-commit via tox"
      run: |
        python -m pip install --upgrade tox tox-gh-actions
        python -m tox
