name: Codecov workflow
on: [push, pull_request]
jobs:
  lint:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: "Install and run pre-commit via tox"
      run: |
        python -m pip install --upgrade tox tox-gh-actions
        python -m tox
