name: Codecov workflow
on: [push, pull_request]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: "Install and run pre-commit via tox"
      run: |
        python -m pip install --upgrade tox tox-gh-actions
        python -m tox
  codecov:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
            python -m pip install --upgrade tox-gh-actions
            python -m pip install -r requirements_dev.txt
    - name: Generate coverage report
      run: "python -m pytest --cov=./ --cov-report=xml"
    - name: Run tox
      run: "python -m tox"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
